### ISSUE TITLE
Tips about changing Decoder model

### ISSUE THREAD

**Issue by acul3** [gchhablani/multilingual-image-captioning#4]
hi @gchhablani 

i'm doing similar jax project but with monolingual language instead of multilingual

i'm planning to use gpt2 as decoder instead of bart

can you give any tips where should i change it?

i notice that FlaxBartDecoder return [cross attention](https://github.com/huggingface/transformers/blob/b29c394586f4a4c64b6f84974dbb9cb847adc5d8/src/transformers/models/bart/modeling_flax_bart.py#L833) 
but Gpt2 only return hidden_states and attention. should that be concern?

thank you before

sorry if this no the right place to put question like this

**Comment by gchhablani** [comment]
@acul3 

I am not sure how GPT2 works, but since it is not an encoder-decoder model, I am not sure if you can do this as easily there. 

@patil-suraj had suggested adding a cross-attention in the model forward and taking in encoder inputs to convert it into a decoder-style model. Then you might be able to use the pre-trained params and use the cross attention with `encoder_hidden_states`.

Now, I also have a `GenerationMixin` with the clip-vision model, so you can also use that then.

Before anything, you should create `GPTDecoder` and check if that works with dummy inputs. I would spend more time on this if I could and provide you with some code, but it can take me some time.

**Comment by acul3** [comment]
@gchhablani thanks for explain 

i'm currently switching to marian model as decoder since it more easy to adapt

and will look gpt2 after

thank you again if you willing spend time and perhaps provide code for changing decoder!!

**Comment by gchhablani** [comment]
Hi @acul3

Someone has already prepared a code for ViT-GPT2 here : https://github.com/ydshieh/vit-gpt2

**Comment by acul3** [comment]
@gchhablani thank you for link

will try to look at it
